version: '3.9'

services:

  postgres:
    container_name: movie_control_api_postgres_db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /data/postgres
    volumes:
      - movie-control-postgres-db-data:/data/postgres
    ports:
      - "5432:5432"

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - movie-control-api
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - movie-control-api

networks:
  movie-control-api:
    driver: bridge

volumes:
  movie-control-postgres-db-data:
    driver: local
  prometheus_data:
  grafana_data: