
server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none

tmdb:
  url: https://api.themoviedb.org/3
  language: pt-BR
  api-key: ce6047be362c9ee238245147b61f2d66
  token: Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJjZTYwNDdiZTM2MmM5ZWUyMzgyNDUxNDdiNjFmMmQ2NiIsInN1YiI6IjY1YjZlNTRlMGNkMzJhMDE3Y2U1YmQ0NyIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.my-7zbADyvlZ_KKfYTIAEtX_bTvWAtnqMxVlwrbmOqs
  endpoint:
    search:
      movie: /search/movie
    movie:
      get-by-id: /movie/{id}
      genre:
        list: /genre/movie/list
    languages: /configuration/languages

viacep:
  url : https://viacep.com.br
  endpoint:
    get-by-cep: /ws/{cep}/json

api:
  security:
    token:
      secret: ${JWT_SECRET:my-secret-key}
    issuer: movie-control-api